default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: root
  timeout: 5000
  port: 5432
  socket: /var/run/postgresql

development:
  <<: *default
  url:  <%= ENV["DATABASE_URL_DEV"] %>

test:
  # adapter: postgresql
  url:  <%= ENV["DATABASE_URL"] %>
  # pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

production:
  url:  <%= ENV["DATABASE_URL"] %>
  # pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
